name: Validate with hassfest

on:
  push:
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "CLAUDE.md"
      - "README.md"
      - "CHANGELOG.md"
      - "CONTRIBUTING.md"
  pull_request:
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "CLAUDE.md"
      - "README.md"
      - "CHANGELOG.md"
      - "CONTRIBUTING.md"
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "home-assistant/actions/hassfest@master"
